@extends('layouts/layout')

@section ('pageTitle','Posts')

@section('content')

<h1 class="text-center">Editing Post : {{$post->id}}</h1>


<form method="POST" action="/posts/{{ $post->id }}">

    {{ method_field("PATCH") }}
    {{ csrf_field() }}

    <div class="form-group">
        <label for="titleInput">Title</label>
        <input id="titleInput" type="text" name="title" value="{{ $post->title }}" class="form-control" onchange="setSlugField(this.value)">
        <small class="form-text text-muted">Enter the post title here</small>
    </div>

    <div class="form-group">
        <label for="subtitleInput">Subtitle</label>
        <input id="subtitleInput" type="text" name="subtitle" value="{{ $post->subtitle }}" class="form-control">
        <small class="form-text text-muted">Enter the post subtitle here</small>
    </div>

    <div class="form-group">
        <label for="slugInput">Slug</label>
        <input id="slugInput" type="text" name="slug" value="{{ $post->slug }}" class="form-control" readonly>
        <small class="form-text text-muted">Slug is an autogenerated field</small>
    </div>

    <div class="form-group">
        <label for="categoriesShow">The Posts currently belongs to the following categories:</label>
        <div>
            @if ($post->categories->isEmpty())
            <p>Categories not assigned</p>
            @else
            @foreach ($post->categories as $cat)
            <span class="mx-2 py-2 px-3" style="background-color: grey; border-radius:10px;">
                <a style="color: white;">{{ $cat->title }}</a>
            </span>
            @endforeach
            @endif
        </div>
        <small class="form-text text-muted">Please update categories below</small>
    </div>

    <div class="form-row">
        <div class=" col-6 form-group">
            <label for="categoriesInput">Categories</label>
            <select multiple name="categories[]" class="form-control">
                @foreach ($categories as $cat)
                <option value="{{ $cat->id }}">{{ $cat->title }}</option>
                @endforeach
            </select>
            <small class="form-text text-muted">Hold down the Ctrl (windows) or Command (Mac) button to select multiple options.</small>
        </div>
        <div class="col-6 form-group">
            <label for="dateInput">Pub. Date</label>
            <input type="date" id="dateInput" name="publish_at" value="{{ $post->publish_at->toDateString() }}" class="form-control {{ $errors->has('publish_at') ? 'is-invalid' : ''}}">
        </div>
    </div>

    <div class="form-group">
        <label for="contentInput">Content</label>
        <textarea id="contentInput" name="content" class="form-control">{{ $post->content }}</textarea>
        <small class="form-text text-muted">Slug is an autogenerated field</small>
    </div>

    <div class="form-group">
        <div class="custom-file mb-3">
            <input type="file" class="custom-file-input" id="validatedCustomFile">
            <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
            <div class="invalid-feedback">Example invalid custom file feedback</div>
        </div>
    </div>



    <button type="submit" class="btn btn-primary" style="width: 100%;">Update Post </button>

</form>

<form method="POST" action="/posts/{{ $post->id }}" class="mt-2">
    {{ method_field("DELETE") }}
    {{ csrf_field() }}

    <button type="button" id="delete" class="btn btn-danger" style="width: 100%;">Delete Post</button>

</form>

@endsection