@extends('layouts/layout')

@section ('pageTitle','Posts')

@section('content')

<h1 class="text-center">Editing Category with ID : {{$category->id}}</h1>

<form method="POST" action="/categories/{{ $category->id }}">

    {{ method_field("PATCH") }}
    {{ csrf_field() }}

    <div class="form-group">
        <label for="titleInput">Title</label>
        <input id="titleInput" type="text" name="title" value="{{ $category->title }}" class="form-control" onchange="setSlugField(this.value)">
        <small class="form-text text-muted">Enter the category title here</small>
    </div>

    <div class="form-group">
        <label for="slugInput">Slug</label>
        <input id="slugInput" type="text" name="slug" value="{{ $category->slug }}" class="form-control" readonly>
        <small class="form-text text-muted">Slug is an autogenerated field</small>
    </div>

    <button type="submit" class="btn btn-primary" style="width: 100%;">Update Category</button>

</form>

<form method="POST" action="/categories/{{ $category->id }}" class="mt-2">
    {{ method_field("DELETE") }}
    {{ csrf_field() }}

    <button type="button" id="delete" class="btn btn-danger" style="width: 100%;">Delete Category</button>

</form>

@endsection